package com.hishop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hishop.entity.Goods;

public interface IGoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    Goods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    int updateByPrimaryKey(Goods record);

	List<Goods> selectGoods(@Param("goodsName")String goodsName, @Param("goodsCode")String goodsCode, @Param("categoryId")Integer categoryId);

	String getChildCaIds(Integer categoryId);
}