package com.hishop.entity;

import java.io.Serializable;
import java.util.Date;

public class Category implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 5155275213163334877L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.parentId
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.hierarchy
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private Integer hierarchy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.categoryName
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.createTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.createUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updateTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.updateUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    private String updateuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.parentId
     *
     * @return the value of category.parentId
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.parentId
     *
     * @param parentid the value for category.parentId
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.hierarchy
     *
     * @return the value of category.hierarchy
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public Integer getHierarchy() {
        return hierarchy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.hierarchy
     *
     * @param hierarchy the value for category.hierarchy
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setHierarchy(Integer hierarchy) {
        this.hierarchy = hierarchy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.categoryName
     *
     * @return the value of category.categoryName
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.categoryName
     *
     * @param categoryname the value for category.categoryName
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.createTime
     *
     * @return the value of category.createTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.createTime
     *
     * @param createtime the value for category.createTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.createUser
     *
     * @return the value of category.createUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.createUser
     *
     * @param createuser the value for category.createUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updateTime
     *
     * @return the value of category.updateTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updateTime
     *
     * @param updatetime the value for category.updateTime
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.updateUser
     *
     * @return the value of category.updateUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public String getUpdateuser() {
        return updateuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.updateUser
     *
     * @param updateuser the value for category.updateUser
     *
     * @mbggenerated Tue May 22 15:51:20 CST 2018
     */
    public void setUpdateuser(String updateuser) {
        this.updateuser = updateuser == null ? null : updateuser.trim();
    }
}