package com.hishop.entity;

import java.io.Serializable;

import com.hishop.common.GoodsStatus;

public class Goods implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 5909442439781903847L;

    private Long id;
    private Integer categoryid;
    private String goodsname;
    private String goodscode;
    private Long inventory;

    private Long costprice;

    private Long fixedprice;

    private Long marketprice;

    private int goodStatus;

    private String image;

    private byte[] goodsdesc;
    
    private String cid;
    
    private String cname;
    
    private String content;
    
    private String contentCopy;

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.categoryId
     *
     * @return the value of goods.categoryId
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.categoryId
     *
     * @param categoryid the value for goods.categoryId
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsName
     *
     * @return the value of goods.goodsName
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsName
     *
     * @param goodsname the value for goods.goodsName
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsCode
     *
     * @return the value of goods.goodsCode
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public String getGoodscode() {
        return goodscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsCode
     *
     * @param goodscode the value for goods.goodsCode
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setGoodscode(String goodscode) {
        this.goodscode = goodscode == null ? null : goodscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.inventory
     *
     * @return the value of goods.inventory
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public Long getInventory() {
        return inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.inventory
     *
     * @param inventory the value for goods.inventory
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setInventory(Long inventory) {
        this.inventory = inventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.costPrice
     *
     * @return the value of goods.costPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public Long getCostprice() {
        return costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.costPrice
     *
     * @param costprice the value for goods.costPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setCostprice(Long costprice) {
        this.costprice = costprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.fixedPrice
     *
     * @return the value of goods.fixedPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public Long getFixedprice() {
        return fixedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.fixedPrice
     *
     * @param fixedprice the value for goods.fixedPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setFixedprice(Long fixedprice) {
        this.fixedprice = fixedprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.marketPrice
     *
     * @return the value of goods.marketPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public Long getMarketprice() {
        return marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.marketPrice
     *
     * @param marketprice the value for goods.marketPrice
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setMarketprice(Long marketprice) {
        this.marketprice = marketprice;
    }


	public int getGoodStatus() {
		return goodStatus;
	}

	public void setGoodStatus(int goodStatus) {
		this.goodStatus = goodStatus;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.image
     *
     * @return the value of goods.image
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.image
     *
     * @param image the value for goods.image
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsDesc
     *
     * @return the value of goods.goodsDesc
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public byte[] getGoodsdesc() {
        return goodsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsDesc
     *
     * @param goodsdesc the value for goods.goodsDesc
     *
     * @mbggenerated Tue May 22 15:52:30 CST 2018
     */
    public void setGoodsdesc(byte[] goodsdesc) {
        this.goodsdesc = goodsdesc;
    }

	public String getCid() {
		return cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getContentCopy() {
		return contentCopy;
	}

	public void setContentCopy(String contentCopy) {
		this.contentCopy = contentCopy;
	}
    
	
    
}